enum EnumDataForGameMatchEEMyFirstUserVM {
  isLoading,
  exception,

  thisIsMyPickedKillerWMyTurnToBanTheKillersMaps,
  thisIsMyPickedKillerWEnemyTurnToBanTheKillersMaps,
  thisIsMyPickedKillerWMyTurnToPickTheKillersPerks,
  thisIsMyPickedKillerWEnemyTurnToPickTheKillersPerks,
  thisIsMyPickedKillerWMyTurnToPickTheSurvivorsPerks,
  thisIsMyPickedKillerWEnemyTurnToPickTheSurvivorsPerks,

  thisIsNotMyPickedKillerWEnemyTurnToBanTheKillersMaps,
  thisIsNotMyPickedKillerWMyTurnToBanTheKillersMaps,
  thisIsNotMyPickedKillerWEnemyTurnToPickTheKillersPerks,
  thisIsNotMyPickedKillerWMyTurnToPickTheKillersPerks,
  thisIsNotMyPickedKillerWEnemyTurnToPickTheSurvivorsPerks,
  thisIsNotMyPickedKillerWMyTurnToPickTheSurvivorsPerks,

  thisIsNobodyPickedKillerWMyTurnToBanTheKillersMaps,
  thisIsNobodyPickedKillerWEnemyTurnToBanTheKillersMaps,
  thisIsNobodyPickedKillerWMyTurnToPickTheKillersPerks,
  thisIsNobodyPickedKillerWEnemyTurnToPickTheKillersPerks,
  thisIsNobodyPickedKillerWMyTurnToPickTheSurvivorsPerks,
  thisIsNobodyPickedKillerWEnemyTurnToPickTheSurvivorsPerks,

  thisIsPickedKillerWSystemTurnToPickTheKillersMaps,
  thisIsPickedKillerWSystemTurnToPickTheKillersPerks,
  thisIsPickedKillerWSystemTurnToPickTheSurvivorsPerks,

  myTurnToBanTheKillerInTheFirstStage,
  enemyTurnToBanTheKillerInTheFirstStage,
  myTurnToPickTheKillerInTheFirstStage,
  enemyTurnToPickTheKillerInTheFirstStage,
  myTurnToBanTheKillerInTheSecondStage,
  enemyTurnToBanTheKillerInTheSecondStage,
  systemTurnToPickTheKillerInTheSecondStage,

  thisIsMyPickedKillerInRoundWMyKillerNotReady,
  thisIsMyPickedKillerInRoundWMyKillerReadyAndEnemySurvivorNotReady,
  thisIsMyPickedKillerInRoundWMyKillerReadyAndEnemySurvivorReady,
  thisIsMyPickedKillerInRoundWEnemyKillerNotReady,
  thisIsMyPickedKillerInRoundWEnemyKillerReadyAndMySurvivorNotReady,
  thisIsMyPickedKillerInRoundWEnemyKillerReadyAndMySurvivorReady,

  thisIsNotMyPickedKillerInRoundWEnemyKillerNotReady,
  thisIsNotMyPickedKillerInRoundWEnemyKillerReadyAndMySurvivorNotReady,
  thisIsNotMyPickedKillerInRoundWEnemyKillerReadyAndMySurvivorReady,
  thisIsNotMyPickedKillerInRoundWMyKillerNotReady,
  thisIsNotMyPickedKillerInRoundWMyKillerReadyAndEnemySurvivorNotReady,
  thisIsNotMyPickedKillerInRoundWMyKillerReadyAndEnemySurvivorReady,

  thisIsNobodyPickedKillerInRoundWMyKillerNotReady,
  thisIsNobodyPickedKillerInRoundWMyKillerReadyAndEnemySurvivorNotReady,
  thisIsNobodyPickedKillerInRoundWMyKillerReadyAndEnemySurvivorReady,
  thisIsNobodyPickedKillerInRoundWEnemyKillerNotReady,
  thisIsNobodyPickedKillerInRoundWEnemyKillerReadyAndMySurvivorNotReady,
  thisIsNobodyPickedKillerInRoundWEnemyKillerReadyAndMySurvivorReady,

  completed
}